### ISSUE TITLE
Cannot read property 'code' of null

### ISSUE THREAD

**Issue by sarus** [polarityio/nexpose#1]
```
{
    "debug": {
        "message": "Cannot read property 'code' of null",
        "stack": "TypeError: Cannot read property 'code' of null\n    at Request.request [as _callback] (/app/polarity-server/integrations/nexpose/integration.js:21:23)\n    at Request.self.callback (/app/polarity-server/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.<anonymous> (/app/polarity-server/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:182:13)\n    at IncomingMessage.<anonymous> (/app/polarity-server/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:273:13)\n    at IncomingMessage.emit (events.js:187:15)\n    at endReadableNT (_stream_readable.js:1094:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
    },
    "error-signature": "c444f1f56172217cb63dba7fe4806242"
}
```

**Comment by sarus** [comment]
Fixed in 3.1.0-beta (https://github.com/polarityio/nexpose/releases/tag/3.1.0-beta)
